#!/usr/bin/env ruby
require "erb"

Lab = Struct.new(:l, :a, :b) do
  def delta(other)
    Math.sqrt((l - other.l) ** 2 + (a - other.a) ** 2 + (b - other.b) ** 2)
  end
end

Color = Struct.new(:red, :green, :blue) do
  WHITE = new(255, 255, 255)
  BLACK = new(0, 0, 0)

  def -(other)
    Color.new(
      red - other.red,
      green - other.green,
      blue - other.blue,
    )
  end

  def +(other)
    Color.new(
      red + other.red,
      green + other.green,
      blue + other.blue,
    )
  end

  def ==(other)
    red == other.red &&
      green == other.green &&
      blue == other.blue
  end

  def /(scalar)
    Color.new(
      red / scalar,
      green / scalar,
      blue / scalar,
    )
  end

  def *(scalar)
    Color.new(
      red * scalar,
      green * scalar,
      blue * scalar,
    )
  end

  def anti
    if (WHITE - self).norm > (BLACK - self).norm
      WHITE
    else
      BLACK
    end
  end

  def round
    Color.new(
      red.round,
      green.round,
      blue.round,
    )
  end

  def float
    Color.new(
      red.to_f,
      green.to_f,
      blue.to_f,
    )
  end

  def norm
    Math.sqrt(red ** 2 + green ** 2 + blue ** 2)
  end

  def hex
    sprintf("%02x%02x%02x", red, green, blue)
  end

  def lab
    var_R = ( red.to_f / 255 )
    var_G = ( green.to_f / 255 )
    var_B = ( blue.to_f / 255 )

    if ( var_R > 0.04045 )
      var_R = ( ( var_R + 0.055 ) / 1.055 ) ** 2.4
    else
      var_R = var_R / 12.92
    end

    if ( var_G > 0.04045 )
      var_G = ( ( var_G + 0.055 ) / 1.055 ) ** 2.4
    else
      var_G = var_G / 12.92
    end

    if ( var_B > 0.04045 )
      var_B = ( ( var_B + 0.055 ) / 1.055 ) ** 2.4
    else
      var_B = var_B / 12.92
    end

    var_R = var_R * 100
    var_G = var_G * 100
    var_B = var_B * 100

    x = var_R * 0.4124 + var_G * 0.3576 + var_B * 0.1805
    y = var_R * 0.2126 + var_G * 0.7152 + var_B * 0.0722
    z = var_R * 0.0193 + var_G * 0.1192 + var_B * 0.9505

    var_X = x / 95.047
    var_Y = y / 100.000
    var_Z = z / 108.883

    if ( var_X > 0.008856 )
      var_X = var_X ** ( 1.0/3 )
    else
      var_X = ( 7.787 * var_X ) + ( 16.0 / 116 )
    end

    if ( var_Y > 0.008856 )
      var_Y = var_Y ** ( 1.0/3 )
    else
      var_Y = ( 7.787 * var_Y ) + ( 16.0 / 116 )
    end

    if ( var_Z > 0.008856 )
      var_Z = var_Z ** ( 1.0/3 )
    else
      var_Z = ( 7.787 * var_Z ) + ( 16.0 / 116 )
    end

    Lab.new(
      ( 116 * var_Y ) - 16,
      500 * ( var_X - var_Y ),
      200 * ( var_Y - var_Z ),
    )
  end
end

class String
  def to_color
    color = Color.new
    color.red = self[0...2].to_i(16).to_f
    color.green = self[2...4].to_i(16).to_f
    color.blue = self[4...6].to_i(16).to_f
    color
  end
end

base = File.read(File.join(File.dirname(__FILE__), "base.icls"))

colors = base.scan(/(?<=")[0-9a-f]{6}(?=")/).uniq.map(&:to_color)

groups = colors.map { |color| [color] }

while true
  centers = groups.map { |group| group.reduce(:+).float / group.count }

  distances = centers.map do |lhs|
    centers.map do |rhs|
      lhs.lab.delta(rhs.lab)
    end
  end

  min_distance = Float::INFINITY
  min_i = nil
  min_j = nil
  distances.each_with_index do |row, i|
    row.each_with_index do |distance, j|
      next if i == j
      if distance < min_distance
        min_distance = distance
        min_i = i
        min_j = j
      end
    end
  end

  break if min_distance > 20.0

  groups[min_i] += groups[min_j]
  groups.delete_at(min_j)
end

forced_groups = {
  "f8e71c" => "fbd85c",
  "f49810" => "f59762",
  "86dde9" => "33cccc",
  "ab9df5" => "c7c8f5",
  "9373a5" => "c7c8f5",
  "e6ffd6" => "c1c0c0",
}

forced_groups.each do |source_hex, target_hex|
  source_color = source_hex.to_color
  target_color = target_hex.to_color
  source_group = groups.detect { |group| group.include?(source_color) }
  target_group = groups.detect { |group| group.include?(target_color) }
  if !source_group || !target_group || source_group == target_group
    puts "Group with #{source_hex} or #{target_hex} not found or equal"
    next
  end
  source_group.each { |color| target_group << color }
  groups.delete(source_group)
end

BACKGROUND = "242622"
GREEN = "a2e52c"

group_substitutions = {
  "e91e63" => "c579f8", # lavender
  "2d2a2e" => BACKGROUND, # black
  "c1c0c0" => "fffbf7", # white
  "727072" => "939293", # grey
  "fbd85c" => "ffe135", # yellow
  "f59762" => "fda526", # orange
  "aedc70" => GREEN, # green
  "86dde9" => "66d9ef", # cyan
  "007f00" => GREEN, # green (console)
  "ab9df5" => "fa5b9e", # magenta
}

substitutions = {}

group_substitutions.each do |base_hex, custom_hex|
  base_color = base_hex.to_color
  custom_color = custom_hex.to_color
  group = groups.detect { |group| group.include?(base_color) }
  if group.nil?
    puts "Group with #{base_hex} not found"
    next
  end
  difference = custom_color - base_color
  group.each_with_index do |color, i|
    adjusted = color + difference
    max = [adjusted.red, adjusted.green, adjusted.blue].max
    min = [adjusted.red, adjusted.green, adjusted.blue].min
    upper = [0, [255, max].min].max
    lower = [0, [255, min].min].max
    adjusted -= Color.new(min, min, min)
    adjusted = adjusted.float * (upper - lower) / (max - min)
    adjusted += Color.new(lower, lower, lower)
    adjusted = adjusted.round
    substitutions[color.hex] = adjusted.hex
    group[i] = adjusted
  end
end

preview = ERB.new(<<-ERB).result(binding)
<html>
<body style="font-size: 3.0em; background-color: ##{BACKGROUND};">
<% groups.each do |group| %>
  <div>
    <% group.each do |color| %>
      <span style="font-family: monospace; color: #<%= color.anti.hex %>; background-color: #<%= color.hex %>;">
        <%= color.hex %>
      </span>
    <% end %>
  </div>
<% end %>
</body>
</html>
ERB

File.open(File.join(File.dirname(__FILE__), "preview.html"), "w") do |file|
  file.write(preview)
end

File.open(File.join(File.dirname(__FILE__), "custom.icls"), "w") do |file|
  custom = base
  substitutions.each do |color_hex, adjusted_hex|
    custom.gsub!(/(?<=")#{color_hex}(?=")/, adjusted_hex)
  end
  file.write(custom)
end
